<?php
$title = 'Edit news item';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?= $this->url('news/list'); ?>"><< back</a></p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('news/edit', array(), true));
$form->prepare();

$form->get('submit')->setValue('Update News');

echo $this->partial('_form.phtml', array('form' => $form)); ?>