<?php
$this->headTitle($this->escapeHtml($this->newsItem->getTitle()));
?>
<h1><?php echo $this->escapeHtml($this->newsItem->getTitle()); ?></h1>
<p><a href="<?= $this->url('news'); ?>"><< back</a></p>
<div class="left-menu">
    <?php echo $this->partial('_left_menu.phtml', array('news_archive' => $news_archive, 'by_topic' => $by_topic)); ?>
</div>
<div class="content">
    <div>
        <ul class="list-unstyled breadcrumb">
            <li><?php echo $this->newsItem->getDate(); ?></li>
            <li><?php echo $this->newsItem->getTheme(); ?></li>
        </ul>
        <p>
            <?php echo $this->newsItem->getText(); ?>
        </p>
    </div>
    <p><a href="<?= $this->url('news'); ?>">All news</a></p>
</div>
<div class="delimiter"></div>

